/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CategoryBudget
 */
export interface CategoryBudget {
    /**
     * 
     * @type {string}
     * @memberof CategoryBudget
     */
    'categoryBudgetId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryBudget
     */
    'categoryId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CategoryBudget
     */
    'categoryName'?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryBudget
     */
    'budget'?: number;
}

