/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DashboardCategorySummaryItem } from './dashboard-category-summary-item';
// May contain unused imports in some cases
// @ts-ignore
import { DashboardKpi } from './dashboard-kpi';
// May contain unused imports in some cases
// @ts-ignore
import { DashboardTrendItem } from './dashboard-trend-item';

/**
 * 
 * @export
 * @interface DashboardData
 */
export interface DashboardData {
    /**
     * 
     * @type {DashboardKpi}
     * @memberof DashboardData
     */
    'kpi'?: DashboardKpi;
    /**
     * 
     * @type {Array<DashboardCategorySummaryItem>}
     * @memberof DashboardData
     */
    'categorySummary'?: Array<DashboardCategorySummaryItem>;
    /**
     * 
     * @type {Array<DashboardTrendItem>}
     * @memberof DashboardData
     */
    'trendSummary'?: Array<DashboardTrendItem>;
}

