/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExpenseItemBase
 */
export interface ExpenseItemBase {
    /**
     * 
     * @type {string}
     * @memberof ExpenseItemBase
     */
    'productName': string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItemBase
     */
    'quantity': number;
    /**
     * Cena za sztukę, nie może być ujemna
     * @type {number}
     * @memberof ExpenseItemBase
     */
    'price': number;
    /**
     * ID kategorii (opcjonalne, bo OCR może nie rozpoznać)
     * @type {string}
     * @memberof ExpenseItemBase
     */
    'categoryId': string;
}

