/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ExpenseItem } from './expense-item';

/**
 * 
 * @export
 * @interface ExpenseDetails
 */
export interface ExpenseDetails {
    /**
     * 
     * @type {string}
     * @memberof ExpenseDetails
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseDetails
     */
    'transactionDate': string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseDetails
     */
    'totalAmount': number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseDetails
     */
    'itemCount': number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseDetails
     */
    'expenseId': string;
    /**
     * 
     * @type {Array<ExpenseItem>}
     * @memberof ExpenseDetails
     */
    'items': Array<ExpenseItem>;
}

