/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExpenseBase
 */
export interface ExpenseBase {
    /**
     * 
     * @type {string}
     * @memberof ExpenseBase
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseBase
     */
    'transactionDate': string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseBase
     */
    'totalAmount': number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseBase
     */
    'itemCount'?: number;
}

