/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExpenseItem
 */
export interface ExpenseItem {
    /**
     * 
     * @type {string}
     * @memberof ExpenseItem
     */
    'productName': string;
    /**
     * 
     * @type {number}
     * @memberof ExpenseItem
     */
    'quantity': number;
    /**
     * Price per unit, cannot be negative
     * @type {number}
     * @memberof ExpenseItem
     */
    'price': number;
    /**
     * Category ID (optional, as OCR might not recognize it)
     * @type {string}
     * @memberof ExpenseItem
     */
    'categoryId': string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItem
     */
    'expenseItemId': string;
    /**
     * 
     * @type {string}
     * @memberof ExpenseItem
     */
    'categoryName': string;
}

