/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ExpenseSummary } from './expense-summary';

/**
 * Standardowy obiekt odpowiedzi dla paginacji
 * @export
 * @interface ExpenseSummaryPage
 */
export interface ExpenseSummaryPage {
    /**
     * 
     * @type {Array<ExpenseSummary>}
     * @memberof ExpenseSummaryPage
     */
    'content'?: Array<ExpenseSummary>;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSummaryPage
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSummaryPage
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSummaryPage
     */
    'totalPages'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseSummaryPage
     */
    'totalElements'?: number;
}

