/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MonthlySpendingSummaryItem
 */
export interface MonthlySpendingSummaryItem {
    /**
     * 
     * @type {number}
     * @memberof MonthlySpendingSummaryItem
     */
    'month'?: number;
    /**
     * 
     * @type {number}
     * @memberof MonthlySpendingSummaryItem
     */
    'totalSpending'?: number;
    /**
     * 
     * @type {number}
     * @memberof MonthlySpendingSummaryItem
     */
    'budget'?: number;
}

