/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CategoryBudget } from './category-budget';

/**
 * 
 * @export
 * @interface MonthlyBudget
 */
export interface MonthlyBudget {
    /**
     * 
     * @type {string}
     * @memberof MonthlyBudget
     */
    'budgetId'?: string;
    /**
     * 
     * @type {number}
     * @memberof MonthlyBudget
     */
    'year'?: number;
    /**
     * 
     * @type {number}
     * @memberof MonthlyBudget
     */
    'month'?: number;
    /**
     * 
     * @type {number}
     * @memberof MonthlyBudget
     */
    'budget'?: number;
    /**
     * 
     * @type {Array<CategoryBudget>}
     * @memberof MonthlyBudget
     */
    'categoryBudgets'?: Array<CategoryBudget>;
}

