/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NewCategoryBudget } from './new-category-budget';

/**
 * 
 * @export
 * @interface NewMonthlyBudget
 */
export interface NewMonthlyBudget {
    /**
     * 
     * @type {number}
     * @memberof NewMonthlyBudget
     */
    'budget': number;
    /**
     * 
     * @type {number}
     * @memberof NewMonthlyBudget
     */
    'year': number;
    /**
     * 
     * @type {number}
     * @memberof NewMonthlyBudget
     */
    'month': number;
    /**
     * 
     * @type {Array<NewCategoryBudget>}
     * @memberof NewMonthlyBudget
     */
    'categoryBudgets'?: Array<NewCategoryBudget>;
}

