/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NewExpenseItem } from './new-expense-item';

/**
 * 
 * @export
 * @interface NewExpense
 */
export interface NewExpense {
    /**
     * 
     * @type {string}
     * @memberof NewExpense
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof NewExpense
     */
    'transactionDate': string;
    /**
     * List of items. Can be empty if adding just a general expense.
     * @type {Array<NewExpenseItem>}
     * @memberof NewExpense
     */
    'items'?: Array<NewExpenseItem>;
}

