/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { NewShoppingListItem } from './new-shopping-list-item';

/**
 * 
 * @export
 * @interface NewShoppingList
 */
export interface NewShoppingList {
    /**
     * 
     * @type {string}
     * @memberof NewShoppingList
     */
    'name': string;
    /**
     * 
     * @type {Array<NewShoppingListItem>}
     * @memberof NewShoppingList
     */
    'items'?: Array<NewShoppingListItem>;
}

