/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ShoppingListItem } from './shopping-list-item';

/**
 * 
 * @export
 * @interface ShoppingList
 */
export interface ShoppingList {
    /**
     * 
     * @type {string}
     * @memberof ShoppingList
     */
    'shoppingListId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingList
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingList
     */
    'createdAt'?: string;
    /**
     * 
     * @type {Array<ShoppingListItem>}
     * @memberof ShoppingList
     */
    'items'?: Array<ShoppingListItem>;
    /**
     * 
     * @type {number}
     * @memberof ShoppingList
     */
    'itemCount'?: number;
}

