/* tslint:disable */
/* eslint-disable */
/**
 * Smart Receipt API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ShoppingListItem
 */
export interface ShoppingListItem {
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItem
     */
    'shoppingListItemId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItem
     */
    'productName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ShoppingListItem
     */
    'quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItem
     */
    'unit'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShoppingListItem
     */
    'isPurchased'?: boolean;
}

